
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook3;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Label label8;
	private global::Gtk.Label label9;
	private global::Gtk.Label label10;
	private global::Gtk.Label label11;
	private global::Gtk.Label label12;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.Label label5;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.ProgressBar progressbar1;
	private global::Gtk.RadioButton radiobutton1;
	private global::Gtk.Entry entry1;
	private global::Gtk.Button button1;
	private global::Gtk.RadioButton radiobutton2;
	private global::Gtk.Label label1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.Label label4;
	private global::Gtk.Label label6;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView textview2;
	private global::Gtk.Label label7;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("EliteLeech");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook3 = new global::Gtk.Notebook ();
		this.notebook3.CanFocus = true;
		this.notebook3.Name = "notebook3";
		this.notebook3.CurrentPage = 0;
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Program Version:");
		this.fixed2.Add (this.label8);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label8]));
		w1.X = 26;
		w1.Y = 26;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Latest Version:");
		this.fixed2.Add (this.label9);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label9]));
		w2.X = 26;
		w2.Y = 47;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("1.0 Beta");
		this.fixed2.Add (this.label10);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label10]));
		w3.X = 158;
		w3.Y = 26;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("1.0 Beta");
		this.fixed2.Add (this.label11);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label11]));
		w4.X = 158;
		w4.Y = 47;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("News:");
		this.fixed2.Add (this.label12);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label12]));
		w5.X = 26;
		w5.Y = 68;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		this.fixed2.Add (this.GtkScrolledWindow2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.GtkScrolledWindow2]));
		w6.X = 27;
		w6.Y = 90;
		this.notebook3.Add (this.fixed2);
		// Notebook tab
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Home");
		this.notebook3.SetTabLabel (this.fixed2, this.label5);
		this.label5.ShowAll ();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.progressbar1 = new global::Gtk.ProgressBar ();
		this.progressbar1.Name = "progressbar1";
		this.fixed1.Add (this.progressbar1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.progressbar1]));
		w8.X = 2;
		w8.Y = 275;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Video"));
		this.radiobutton1.CanFocus = true;
		this.radiobutton1.Name = "radiobutton1";
		this.radiobutton1.DrawIndicator = true;
		this.radiobutton1.UseUnderline = true;
		this.radiobutton1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.radiobutton1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton1]));
		w9.X = 149;
		w9.Y = 86;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.Text = global::Mono.Unix.Catalog.GetString ("http://www.youtube.com/watch?v=yMBFFys8-pc");
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w10.X = 24;
		w10.Y = 17;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Download");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w11.X = 206;
		w11.Y = 30;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Audio"));
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.radiobutton1.Group;
		this.fixed1.Add (this.radiobutton2);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton2]));
		w12.X = 161;
		w12.Y = 133;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w13.X = 29;
		w13.Y = 53;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w14.X = 685;
		w14.Y = 205;
		this.notebook3.Add (this.fixed1);
		global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3 [this.fixed1]));
		w15.Position = 1;
		// Notebook tab
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Download");
		this.notebook3.SetTabLabel (this.fixed1, this.label4);
		this.label4.ShowAll ();
		// Notebook tab
		global::Gtk.Label w16 = new global::Gtk.Label ();
		w16.Visible = true;
		this.notebook3.Add (w16);
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Queue");
		this.notebook3.SetTabLabel (w16, this.label6);
		this.label6.ShowAll ();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview2 = new global::Gtk.TextView ();
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.GtkScrolledWindow1.Add (this.textview2);
		this.notebook3.Add (this.GtkScrolledWindow1);
		global::Gtk.Notebook.NotebookChild w18 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3 [this.GtkScrolledWindow1]));
		w18.Position = 3;
		// Notebook tab
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Error Log");
		this.notebook3.SetTabLabel (this.GtkScrolledWindow1, this.label7);
		this.label7.ShowAll ();
		this.Add (this.notebook3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 936;
		this.DefaultHeight = 486;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.radiobutton1.Clicked += new global::System.EventHandler (this.OnRadiobutton1Clicked);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.radiobutton2.Clicked += new global::System.EventHandler (this.OnRadiobutton2Clicked);
	}
}
